# Generated by Django 3.2.22 on 2023-10-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seismoscope', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
