# Generated by Django 3.2.22 on 2023-10-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seismoscope', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photography', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
