# Generated by Django 3.2.22 on 2023-10-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seismoscope', '0006_alter_userform_photography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='photography',
            field=models.ImageField(upload_to=''),
        ),
    ]
