# Generated by Django 3.2.22 on 2023-10-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seismoscope', '0011_rename_chatmess_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='bPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='')),
                ('username', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
    ]
