# Generated by Django 3.2.22 on 2023-10-08 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seismoscope', '0012_bpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
