# Generated by Django 3.2.22 on 2023-10-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seismoscope', '0014_alter_bpost_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpost',
            name='text',
            field=models.TextField(),
        ),
    ]
