# Generated by Django 3.2.22 on 2023-10-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seismoscope', '0015_alter_bpost_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
