# Generated by Django 3.2.22 on 2023-10-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seismoscope', '0016_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpost',
            name='email',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
