# Generated by Django 3.2.22 on 2023-10-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seismoscope', '0017_bpost_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpost',
            name='image',
        ),
    ]
